version: '3'
services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    depends_on:
     - mongodb
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped
  python-service:
    image: apoorvabhishek/apoorvdocker-demo-multi:2.0
    ports:
     - 5005:5005
    restart: unless-stopped
  python-service-old:
    image: apoorvabhishek/apoorvdocker-demo-multi:1.0
    ports:
     - 5006:5005
    restart: unless-stopped
volumes:
  mongo-data:
    driver: local
